//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavaAssignmentClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="ServiceReference1.HumanResourceXmlWebService")]
    public interface HumanResourceXmlWebService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        JavaAssignmentClient.ServiceReference1.luckyNumberArrayResponse luckyNumberArray(JavaAssignmentClient.ServiceReference1.luckyNumberArray request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<JavaAssignmentClient.ServiceReference1.luckyNumberArrayResponse> luckyNumberArrayAsync(JavaAssignmentClient.ServiceReference1.luckyNumberArray request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        JavaAssignmentClient.ServiceReference1.luckyLottoNumberResponse luckyLottoNumber(JavaAssignmentClient.ServiceReference1.luckyLottoNumber request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<JavaAssignmentClient.ServiceReference1.luckyLottoNumberResponse> luckyLottoNumberAsync(JavaAssignmentClient.ServiceReference1.luckyLottoNumber request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        JavaAssignmentClient.ServiceReference1.findAllJobResponse findAllJob(JavaAssignmentClient.ServiceReference1.findAllJob request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<JavaAssignmentClient.ServiceReference1.findAllJobResponse> findAllJobAsync(JavaAssignmentClient.ServiceReference1.findAllJob request);
        
        // CODEGEN: Parameter 'Job' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Job")]
        JavaAssignmentClient.ServiceReference1.findOneJobResponse findOneJob(JavaAssignmentClient.ServiceReference1.findOneJob request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<JavaAssignmentClient.ServiceReference1.findOneJobResponse> findOneJobAsync(JavaAssignmentClient.ServiceReference1.findOneJob request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="luckyNumberArray", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class luckyNumberArray {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public luckyNumberArray() {
        }
        
        public luckyNumberArray(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="luckyNumberArrayResponse", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class luckyNumberArrayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public luckyNumberArrayResponse() {
        }
        
        public luckyNumberArrayResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="luckyLottoNumber", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class luckyLottoNumber {
        
        public luckyLottoNumber() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="luckyLottoNumberResponse", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class luckyLottoNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public luckyLottoNumberResponse() {
        }
        
        public luckyLottoNumberResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/")]
    public partial class job : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string jobIdField;
        
        private string jobTitleField;
        
        private decimal maxSalaryField;
        
        private bool maxSalaryFieldSpecified;
        
        private decimal minSalaryField;
        
        private bool minSalaryFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string jobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
                this.RaisePropertyChanged("jobId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string jobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                this.jobTitleField = value;
                this.RaisePropertyChanged("jobTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal maxSalary {
            get {
                return this.maxSalaryField;
            }
            set {
                this.maxSalaryField = value;
                this.RaisePropertyChanged("maxSalary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxSalarySpecified {
            get {
                return this.maxSalaryFieldSpecified;
            }
            set {
                this.maxSalaryFieldSpecified = value;
                this.RaisePropertyChanged("maxSalarySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal minSalary {
            get {
                return this.minSalaryField;
            }
            set {
                this.minSalaryField = value;
                this.RaisePropertyChanged("minSalary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minSalarySpecified {
            get {
                return this.minSalaryFieldSpecified;
            }
            set {
                this.minSalaryFieldSpecified = value;
                this.RaisePropertyChanged("minSalarySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllJob", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class findAllJob {
        
        public findAllJob() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllJobResponse", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class findAllJobResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaAssignmentClient.ServiceReference1.job[] @return;
        
        public findAllJobResponse() {
        }
        
        public findAllJobResponse(JavaAssignmentClient.ServiceReference1.job[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findOneJob", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class findOneJob {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string JobId;
        
        public findOneJob() {
        }
        
        public findOneJob(string JobId) {
            this.JobId = JobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findOneJobResponse", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class findOneJobResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaAssignmentClient.ServiceReference1.job Job;
        
        public findOneJobResponse() {
        }
        
        public findOneJobResponse(JavaAssignmentClient.ServiceReference1.job Job) {
            this.Job = Job;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HumanResourceXmlWebServiceChannel : JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HumanResourceXmlWebServiceClient : System.ServiceModel.ClientBase<JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService>, JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService {
        
        public HumanResourceXmlWebServiceClient() {
        }
        
        public HumanResourceXmlWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HumanResourceXmlWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HumanResourceXmlWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HumanResourceXmlWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JavaAssignmentClient.ServiceReference1.luckyNumberArrayResponse JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService.luckyNumberArray(JavaAssignmentClient.ServiceReference1.luckyNumberArray request) {
            return base.Channel.luckyNumberArray(request);
        }
        
        public string luckyNumberArray(int arg0) {
            JavaAssignmentClient.ServiceReference1.luckyNumberArray inValue = new JavaAssignmentClient.ServiceReference1.luckyNumberArray();
            inValue.arg0 = arg0;
            JavaAssignmentClient.ServiceReference1.luckyNumberArrayResponse retVal = ((JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService)(this)).luckyNumberArray(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaAssignmentClient.ServiceReference1.luckyNumberArrayResponse> JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService.luckyNumberArrayAsync(JavaAssignmentClient.ServiceReference1.luckyNumberArray request) {
            return base.Channel.luckyNumberArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaAssignmentClient.ServiceReference1.luckyNumberArrayResponse> luckyNumberArrayAsync(int arg0) {
            JavaAssignmentClient.ServiceReference1.luckyNumberArray inValue = new JavaAssignmentClient.ServiceReference1.luckyNumberArray();
            inValue.arg0 = arg0;
            return ((JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService)(this)).luckyNumberArrayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JavaAssignmentClient.ServiceReference1.luckyLottoNumberResponse JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService.luckyLottoNumber(JavaAssignmentClient.ServiceReference1.luckyLottoNumber request) {
            return base.Channel.luckyLottoNumber(request);
        }
        
        public int luckyLottoNumber() {
            JavaAssignmentClient.ServiceReference1.luckyLottoNumber inValue = new JavaAssignmentClient.ServiceReference1.luckyLottoNumber();
            JavaAssignmentClient.ServiceReference1.luckyLottoNumberResponse retVal = ((JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService)(this)).luckyLottoNumber(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaAssignmentClient.ServiceReference1.luckyLottoNumberResponse> JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService.luckyLottoNumberAsync(JavaAssignmentClient.ServiceReference1.luckyLottoNumber request) {
            return base.Channel.luckyLottoNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaAssignmentClient.ServiceReference1.luckyLottoNumberResponse> luckyLottoNumberAsync() {
            JavaAssignmentClient.ServiceReference1.luckyLottoNumber inValue = new JavaAssignmentClient.ServiceReference1.luckyLottoNumber();
            return ((JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService)(this)).luckyLottoNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JavaAssignmentClient.ServiceReference1.findAllJobResponse JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService.findAllJob(JavaAssignmentClient.ServiceReference1.findAllJob request) {
            return base.Channel.findAllJob(request);
        }
        
        public JavaAssignmentClient.ServiceReference1.job[] findAllJob() {
            JavaAssignmentClient.ServiceReference1.findAllJob inValue = new JavaAssignmentClient.ServiceReference1.findAllJob();
            JavaAssignmentClient.ServiceReference1.findAllJobResponse retVal = ((JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService)(this)).findAllJob(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaAssignmentClient.ServiceReference1.findAllJobResponse> JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService.findAllJobAsync(JavaAssignmentClient.ServiceReference1.findAllJob request) {
            return base.Channel.findAllJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaAssignmentClient.ServiceReference1.findAllJobResponse> findAllJobAsync() {
            JavaAssignmentClient.ServiceReference1.findAllJob inValue = new JavaAssignmentClient.ServiceReference1.findAllJob();
            return ((JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService)(this)).findAllJobAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JavaAssignmentClient.ServiceReference1.findOneJobResponse JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService.findOneJob(JavaAssignmentClient.ServiceReference1.findOneJob request) {
            return base.Channel.findOneJob(request);
        }
        
        public JavaAssignmentClient.ServiceReference1.job findOneJob(string JobId) {
            JavaAssignmentClient.ServiceReference1.findOneJob inValue = new JavaAssignmentClient.ServiceReference1.findOneJob();
            inValue.JobId = JobId;
            JavaAssignmentClient.ServiceReference1.findOneJobResponse retVal = ((JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService)(this)).findOneJob(inValue);
            return retVal.Job;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaAssignmentClient.ServiceReference1.findOneJobResponse> JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService.findOneJobAsync(JavaAssignmentClient.ServiceReference1.findOneJob request) {
            return base.Channel.findOneJobAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaAssignmentClient.ServiceReference1.findOneJobResponse> findOneJobAsync(string JobId) {
            JavaAssignmentClient.ServiceReference1.findOneJob inValue = new JavaAssignmentClient.ServiceReference1.findOneJob();
            inValue.JobId = JobId;
            return ((JavaAssignmentClient.ServiceReference1.HumanResourceXmlWebService)(this)).findOneJobAsync(inValue);
        }
    }
}
